Fix documentation for provider getTransactionStatus
0xs34n/starknet.js pull request #202
Opened 2022-06-07 10:35 UTC by ivpavici

2022-06-09 07:06 UTC, MilGard91 requested changes

2022-06-09 07:06 UTC, MilGard91 commented on src/provider/interface.ts
> +   * [Reference] (https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/services/api/feeder_gateway/feeder_gateway_client.py#L104-L111)
Link should be https://github.com/starkware-libs/cairo-lang/blob/167b28bcd940fd25ea3816204fa882a0b0a49603/src/starkware/starknet/services/api/feeder_gateway/feeder_gateway_client.py#L183

And is it only tx hash?

2022-06-09 12:05 UTC, MilGard91 approved these changes

2022-06-13 15:28 UTC, badurinantun approved these changes

2022-06-14 14:52 UTC, closed without merging