fix: tsup config
0xs34n/starknet.js pull request #413
Opened 2022-11-23 14:06 UTC by janek26

This PR fixes the build process.
The current package published at npm (next) does not work due to bad compiling
This PR should fix that. Tested with cjs and esm imports

2022-11-23 14:11 UTC, dhruvkelawala commented
Works! Thanks @janek26

2022-11-24 05:37 UTC, penovicp requested changes
> This PR fixes the build process. The current package published at npm (next) does not work due to bad compiling This PR should fix that. Tested with cjs and esm imports

The `cjs` and `esm` build results of this branch don't differ from those found in the published `4.13.1` module. Here are the comparisons:
- [cjs](https://www.diffchecker.com/lrBt8FWt)
- [esm](https://www.diffchecker.com/wkc1Wvmt)

I'm guessing that the issue that motivated this PR arose from some import/bundling tool that did not utilize `main/module/browser` from `package.json` and that adding `exports` resolved it. I suggest first testing if just the `exports` addition with the `index.mjs` and `index.global.js` files would be sufficient, and if it is not then adding the `legacyOutput` parameter.

2022-11-24 05:37 UTC, penovicp commented on package.json
> +    "build": "tsup",
This and the `tsup.config.ts` change of running all the build outputs together will result in an unusable `iife` build result. The `ethereum-cryptography` dependency has a `@noble/hashes` sub-dependency which necessitates that the different build outputs are run with different values of the `tsup` `platform` parameter, `node` (the default value) for `cjs` and `esm`, `browser` for `iife`. Building `iife` with the default value will result in the code attempting to import the native `node.js` `crypto` module in the browser which will fail (search for `node_modules/@noble/hashes/crypto` in the `iife` build result to find the relevant section of code).

Once issue #405 is resolved (probably when PR #399 is finalized) the build script can be revisited and unified as a single `tsup` invocation.

2022-11-24 05:37 UTC, penovicp commented on tsconfig.json
> +    "declarationMap": true /* Create sourcemaps for d.ts files. */,
This setting will be ignored by `tsup`, the `.d.ts` bundling is done by `rollup-plugin-dts` which does not support declaration mapping ([link]( https://github.com/egoist/tsup/issues/311)).

2022-11-24 05:37 UTC, penovicp commented on tsconfig.json
> +    "target": "ES2020" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
This change is fine but won't actually change the build result.

2022-11-25 09:49 UTC, janek26 commented
thank you so much for the review, this has been super helpful!
I replaced this PR by #418 which fixes our issues!

2022-11-25 09:49 UTC, closed without merging