decodeShortString was not handling properly Integer Strings
0xs34n/starknet.js pull request #508
Opened 2023-02-01 12:42 UTC by PhilippeR26

Fix #501 

## Motivation and Resolution

The function decodeShortString returns a wrong answer  if the input is a string representing an integer.
See issue #501 for example of bug.

Now, the answer is correct

## Usage related changes

No change for users ; just a correct answer of the function

## Development related changes

No impact on development.

## Checklist:

- [X] Performed a self-review of the code
- [X] Rebased to the last commit of the target branch (or merged it into my branch)
- [X] Linked the issues which this PR resolves
- [X] Updated the docs (www)
- [X] Updated the tests
- [ ] All tests are passing

2023-02-01 17:57 UTC, tabaktoni approved these changes

2023-02-01 18:02 UTC, tabaktoni commented
Note: I think it would be cool to create encodeString &. decodeString that will auto-detect length and deal with short and long strings, so that end user has no worry about string length.

2023-02-01 18:24 UTC, PhilippeR26 commented
> Note: I think it would be cool to create encodeString &. decodeString that will auto-detect length and deal with short and long strings, so that end user has no worry about string length.

It could be a problem on Cairo contract side ; some contracts are waiting only a felt (only shortString), some others are waiting only array of felt (long String).
Unfortunately, Cairo is not Typescript : it can not handle several types (as `felt | felt[]` ) and adapt itself in accordance.

2023-02-02 05:39 UTC, penovicp requested changes
Left a minor nitpick for the content changes.

Aside from that at least one of the commits should be reworded to conform to the [conventional commits format](https://www.conventionalcommits.org/en/v1.0.0/) so the patch number of the version is bumped by the CI. I recommend rebasing and squashing the commits into one with a message such as: `fix: repair decodeShortString for integer strings`.

2023-02-02 05:39 UTC, penovicp commented on www/docs/guides/define_call_message.md
> +In Javascript/Typecript, the max length of a string is nearly illimited. In Cairo, a string is limited to only 31 characters, and is called a ShortString.
Nitpick, `limitless` is more commonly used in favour of `illimited`.

2023-02-02 08:12 UTC, tabaktoni commented
> It could be a problem for encode and send to Cairo contract ; some contracts are waiting only a felt (only shortString), some others are waiting only array of felt (long String). Unfortunately, Cairo is not Typescript : it can not handle several types (as `felt | felt[]` ) and adapt itself in accordance. May be on decode side, if you are sure to recover a shortString or a longString, a function 'decodeString' could handle both cases.

This is more comment on the contract class implementation (I can implement it in a contract).
Agree, but when building call/invoke by contract class we read abi, so we know what parameter it expects felt or felt*, and at the same time we validate it against provided arguments. In case the argument is 'very long string.........' and abi element is felt* I can use a long string. In case it is felt and 'very long string...' i can throw error, in case it is felt and 'short string' all ok, in all other cases throw an error.

2023-02-02 08:22 UTC, tabaktoni commented on www/docs/guides/define_call_message.md
> +3. The JS code hast to decode/merge the BNs received from a call.
```suggestion
3. The JS code has to decode/merge the BNs received from a call.
```

2023-02-02 09:27 UTC, ivpavici commented on __tests__/utils/shortString.test.ts
> +  test('should convert decimal number string to string', () => {
nitpick: in general tests in other suites have new lines between them, so maybe to keep the same convention :)

2023-02-02 10:16 UTC, ivpavici approved these changes

2023-02-02 10:36 UTC, PhilippeR26 commented
I think I have all implemented.

2023-02-02 11:22 UTC, penovicp approved these changes

2023-02-02 11:22 UTC, merged