608 bump ts version
0xs34n/starknet.js pull request #612
Opened 2023-05-09 14:01 UTC by notV4l

rel : #608 
-update typescript to 5.0.4 & related dependencies
-update typescript & related dependencies for doc generation in /www

## Checklist:

- [x] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [x] All tests are passing

2023-05-10 07:48 UTC, penovicp requested changes
Remove the `www/docs/API/` changes, documentation updates will be handled by the CI fairly soon which should also keep the code links accurate.

2023-05-17 14:40 UTC, tabaktoni approved these changes
lgtm

2023-05-17 21:49 UTC, ivpavici approved these changes

2023-05-18 04:05 UTC, penovicp approved these changes

2023-05-18 04:07 UTC, merged