Add RawArgsObject in myCallData.compile, with reorder of the properties
0xs34n/starknet.js pull request #619
Opened 2023-05-18 15:23 UTC by PhilippeR26

## Motivation and Resolution

Improvement :
- `CallData.compile` accepts as input the `RawArgArray` and `RawArgsObject` types, but `myCallData.compile` accepts only `RawArgArray`.
- As this method has access to the contract ABI, it should be possible to send it objects whose properties are not ordered (as in any regular JS/TS objects).

utils/calldata is modified to solve these 2 subjects.

## Usage related changes

- Users will be able to prepare their constructor calls with `myCallData.compile`, using RawArgsObject.
- It works for both Cairo 0 and 1.
- Objects (including Uint256) are reordered in conformity with abi.
- If user added properties that are not in ABI, they are ignored.
- If user forgot one property, the call to provider/node will not be done ; a clear and explicit message will be sent as error (Starknet error messages are not really explicit).
- If user add a property array_len before  an array (seen several times in Discord), the propery is ignored, and the call succeeds anyway. 

## Development related changes

- Test for Cairo 0 are in contract.test.ts
- Test for Cairo 1 are in cairo1.test.ts

## Hypothesis:

For Cairo 1, hypothesis have been taken for complex tuple.
It's expected to have this format :
```typescript 
((core::integer::u8, core::integer::u16), core::integer::u256)
```
or 
```typescript 
(core::integer::u256, test_constructor4::test_constructor4::TestConstructor4::Order2, core::array::Array::<core::integer::u128>, core::integer::u64)
```
Code has been created in accordance. 

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [ ] All tests are passing

2023-05-19 10:28 UTC, tabaktoni requested changes

2023-05-19 13:21 UTC, tabaktoni commented on src/utils/calldata/index.ts
> +    return abiMethod.inputs.reduce(
I think with inputs is fine ;)

2023-05-19 13:46 UTC, penovicp commented on src/utils/calldata/propertyOrder.ts
> +  const orderTuple = (myObj: RawArgsObject, abiParam: AbiEntry): object => {
Similar suggestions as `orderStruct`.

2023-05-21 13:50 UTC, PhilippeR26 commented on src/utils/calldata/propertyOrder.ts
> +function errorU256(key: string) {
Sorry, I don't understand your proposal. I understood that the `throw` command needs as parameter an object, and here you proposes a function.
Could you develop?

2023-05-21 14:01 UTC, PhilippeR26 commented on src/utils/calldata/propertyOrder.ts
> +function errorU256(key: string) {
Sorry, I don't understand your proposal. I understood that the `throw` command needs as parameter an object, and here you proposes a function.
Could you develop?

2023-05-21 14:45 UTC, PhilippeR26 commented on src/utils/calldata/propertyOrder.ts
> +          break;
I have modified with this spirit, but as `if` is a way to filter types, I can't have something so flatten.

2023-05-21 14:46 UTC, PhilippeR26 commented on src/utils/calldata/propertyOrder.ts
> +  const orderStruct = (myObj: RawArgsObject, abiObject: AbiEntry[]): object => {
Done.

2023-05-21 16:26 UTC, PhilippeR26 commented
Except `Error`  request of Petar, all is implemented.

2023-05-22 07:52 UTC, penovicp commented on src/utils/calldata/propertyOrder.ts
> +function errorU256(key: string) {
The suggestion is to change the function from returning `void` and throwing internally to just returning an `Error`.

Function change:
```
function errorU256(key: string) {
  return Error(...);
}
```
Usage change:
```
// from
errorU256(abiParam.name);

// to
throw errorU256(abiParam.name);
```

The main benefit of this approach is that most code analysis tools disregard the internal throw even if it is guaranteed to always happen, for example placing `errorU256(...)` at the start of a method wouldn't generate an `unreachable code` warning for the rest of the method code while placing `throw errorU256(...)` would.

2023-05-22 08:50 UTC, PhilippeR26 commented
All is now implemented.

2023-05-25 08:57 UTC, penovicp approved these changes

2023-05-25 09:29 UTC, merged